import Window from "@/components/window";
import { useRef, useState } from "react";

export default function Terminal({
  startingPosition,
  terminalOpen,
  setTerminalOpen,
  id,
  windowOrder,
  setWindowOrder,
  setTerminalOrder,
}: {
  startingPosition: { x: number; y: number };
  terminalOpen: boolean;
  setTerminalOpen: React.Dispatch<React.SetStateAction<boolean>>;
  id: string;
  windowOrder: string[];
  setWindowOrder: React.Dispatch<React.SetStateAction<string[]>>;
  setTerminalOrder: React.Dispatch<React.SetStateAction<string[]>>;
}) {
  const [terminalInput, setTerminalInput] = useState<string>(
    'Welcome to the Pit Wall.\nType the "help" command to see a list of all available commands.\n',
  );
  const textAreaRef = useRef<HTMLTextAreaElement>(null);

  const funFacts: string[] = [
    "Sebastian Vettel is currently the first and only driver to win a race with a Ferrari engine inside of a non-Ferrari car in Monza 2008.",
    "Toro Rosso won their first F1 race before Red Bull did.",
    "Sebastian Vettel won both Toro Rosso and Red Bull their first races.",
    "Jenson Button got a historic 70-place grid penalty in Mexico 2015.",
    "Brawn GP won every WDC and WCC they ever competed in.",
    "Michael Schumacher is the only driver to win 5 WDCs in a row.",
    "Max Verstappen is the only driver to win 10 GPs in a row.",
    "Max Verstappen has the highest percentage of race wins in a single season with 86.36%.",
    "Max Verstappen has the record for most races won in a single season with 19 out of 22 won back in 2023.",
    "Ferrari has the most WCC wins with 16.",
    "The first can of Red Bull was sold in the same year that Sebastian Vettel was born—1987.",
    "2026 is Cadillac's first season competing in F1.",
    "Max Verstappen is the youngest ever race winner.",
    "Esteban Ocon won Alpine their first and currently only F1 race at the 2021 Hungarian Grand Prix.",
  ];

  const quotes: string[] = [
    '"Sometimes you\'ve just got to lick the stamp and send it." - Daniel Ricciardo',
    '"No, Michael, no! That was so not right." - Toto Wolff',
    '"Aerodynamics are for people who can\'t build engines." - Enzo Ferrari',
    '"To achieve anything in this game, you must be prepared to dabble in the boundary of disaster.” - Stirling Moss',
    '"To do something well is so worthwhile that to die trying to do it better cannot be foolhardy. It would be a waste of life to do nothing with one\'s ability, for I feel that life is measured in achievement, not in years alone." - Bruce McLaren',
    '"I am an artist. The track is my canvas and my car is my brush." - Graham Hill',
    '"If you no longer go for a gap that exists, you’re no longer a racing driver." - Ayrton Senna',
    '"I\'ve always believed that you should never, ever give up and you should always keep fighting even when there’s only a slightest chance." - Michael Schumacher',
    '"We win and lose together." - Lewis Hamilton',
    '"Just leave me alone, I know what to do." - Kimi Räikkönen',
    '"Unless I\'m very much mistaken... I am very much mistaken!" - Murray Walker',
    '"Is there a leakage?" - Charles Leclerc',
    '"I have the seat full of water. Like full of water." - Charles Leclerc',
    '"Must be the water." - Bryan Bozzi',
    '"Let\'s add that to the words of wisdom." - Charles Leclerc',
    '"Is Charles catching him or not?" - Max Verstappen',
    '"Oh my lord, Max! Oh my god! You are the world champion! The world champion!" - Gianpiero Lambiase',
    '"Du bist Weltmeister!" - Guillaume Rocquelin',
    '"Is this the world champion hotline?" - Zac Brown',
    '"GP2 engine! GP2!" - Fernando Alonso',
    '"The engine feels good, much slower than before. Amazing." - Fernando Alonso',
    '"At 1:46 am on September 23rd 2024, Daniel Ricciardo exited the F1 paddock for what everybody believes is the last time as an F1 driver." - Kym Illman',
  ];

  //no i didn't do this manually
  const drivers: string[] = [
    "Carlo Abate",
    "George Abecassis",
    "Kenny Acheson",
    "Andrea de Adamich",
    "Philippe Adams",
    "Walt Ader",
    "Kurt Adolff",
    "Fred Agabashian",
    "Kurt Ahrens Jr.",
    "Jack Aitken",
    "Christijan Albers",
    "Alexander Albon",
    "Michele Alboreto",
    "Jean Alesi",
    "Jaime Alguersuari",
    "Ray Allen",
    "Philippe Alliot",
    "Cliff Allison",
    "Fernando Alonso",
    "Giovanna Amati",
    "George Amick",
    "Red Amick",
    "Chris Amon",
    "Bob Anderson",
    "Conny Andersson",
    "Emil Andres",
    "Mario Andretti",
    "Michael Andretti",
    "Keith Andrews",
    "Elio de Angelis",
    "Kimi Antonelli",
    "Marco Apicella",
    "Mário de Araújo Cabral",
    "Frank Armi",
    "Chuck Arnold",
    "René Arnoux",
    "Peter Arundell",
    "Alberto Ascari",
    "Peter Ashdown",
    "Ian Ashley",
    "Gerry Ashmore",
    "Bill Aston",
    "Richard Attwood",
    "Manny Ayulo",
    "Luca Badoer",
    "Giancarlo Baghetti",
    "Julian Bailey",
    "Mauro Baldi",
    "Bobby Ball",
    "Marcel Balsa",
    "Lorenzo Bandini",
    "Henry Banks",
    "Fabrizio Barbazza",
    "John Barber",
    "Skip Barber",
    "Paolo Barilla",
    "Rubens Barrichello",
    "Michael Bartels",
    "Edgar Barth",
    "Giorgio Bassi",
    "Erwin Bauer",
    "Zsolt Baumgartner",
    "Élie Bayol",
    "Oliver Bearman",
    "Don Beauman",
    "Karl-Günther Bechem",
    "Jean Behra",
    "Derek Bell",
    "Stefan Bellof",
    "Paul Belmondo",
    "Tom Belsø",
    "Jean-Pierre Beltoise",
    "Olivier Beretta",
    "Allen Berg",
    "Georges Berger",
    "Gerhard Berger",
    "Éric Bernard",
    "Enrique Bernoldi",
    "Enrico Bertaggia",
    "Tony Bettenhausen",
    "Mike Beuttler",
    "Birabongse Bhanudej",
    "Jules Bianchi",
    "Lucien Bianchi",
    "Gino Bianco",
    "Hans Binder",
    "Clemente Biondetti",
    "Pablo Birger",
    "Art Bisch",
    "Harry Blanchard",
    "Michael Bleekemolen",
    "Alex Blignaut",
    "Trevor Blokdyk",
    "Mark Blundell",
    "Raul Boesel",
    "Menato Boffa",
    "Bob Bondurant",
    "Felice Bonetto",
    "Jo Bonnier",
    "Roberto Bonomi",
    "Juan Manuel Bordeu",
    "Slim Borgudd",
    "Gabriel Bortoleto",
    "Luki Botha",
    "Valtteri Bottas",
    "Jean-Christophe Boullion",
    "Sébastien Bourdais",
    "Thierry Boutsen",
    "Johnny Boyd",
    "David Brabham",
    "Gary Brabham",
    "Jack Brabham",
    "Bill Brack",
    "Ernesto Brambilla",
    "Vittorio Brambilla",
    "Toni Branca",
    "Gianfranco Brancatelli",
    "Eric Brandon",
    "Don Branson",
    "Tom Bridger",
    "Tony Brise",
    "Chris Bristow",
    "Peter Broeker",
    "Tony Brooks",
    "Alan Brown",
    "Walt Brown",
    "Warwick Brown",
    "Adolf Brudes",
    "Martin Brundle",
    "Gianmaria Bruni",
    "Jimmy Bryan",
    "Clemar Bucci",
    "Ronnie Bucknum",
    "Ivor Bueb",
    "Sébastien Buemi",
    "Luiz Bueno",
    "Ian Burgess",
    "Luciano Burti",
    "Roberto Bussinello",
    "Jenson Button",
    "Tommy Byrne",
    "Giulio Cabianca",
    "Phil Cade",
    "Alex Caffi",
    "John Campbell-Jones",
    "Adrián Campos",
    "John Cannon",
    "Eitel Cantoni",
    "Bill Cantrell",
    "Ivan Capelli",
    "Piero Carini",
    "Duane Carter",
    "Eugenio Castellotti",
    "Johnny Cecotto",
    "Andrea de Cesaris",
    "François Cevert",
    "Eugène Chaboud",
    "Jay Chamberlain",
    "Karun Chandhok",
    "Alain de Changy",
    "Colin Chapman",
    "Dave Charlton",
    "Pedro Chaves",
    "Bill Cheesbourg",
    "Eddie Cheever",
    "Andrea Chiesa",
    "Max Chilton",
    "Ettore Chimeri",
    "Louis Chiron",
    "Joie Chitwood",
    "Bob Christie",
    "Johnny Claes",
    "David Clapham",
    "Jim Clark",
    "Kevin Cogan",
    "Franco Colapinto",
    "Peter Collins",
    "Bernard Collomb",
    "Alberto Colombo",
    "Érik Comas",
    "Franco Comotti",
    "George Connor",
    "George Constantine",
    "John Cordts",
    "David Coulthard",
    "Piers Courage",
    "Chris Craft",
    "Jim Crawford",
    "Ray Crawford",
    "Alberto Crespo",
    "Antonio Creus",
    "Larry Crockett",
    "Tony Crook",
    "Art Cross",
    "Geoffrey Crossley",
    "Jérôme d'Ambrosio",
    "Chuck Daigh",
    "Yannick Dalmas",
    "Derek Daly",
    "Christian Danner",
    "Jorge Daponte",
    "Anthony Davidson",
    "Jimmy Davies",
    "Colin Davis",
    "Jimmy Daywalt",
    "Jean-Denis Delétraz",
    "Patrick Depailler",
    "Pedro Diniz",
    "Duke Dinsmore",
    "Frank Dochnal",
    "José Dolhem",
    "Martin Donnelly",
    "Mark Donohue",
    "Jack Doohan",
    "Robert Doornbos",
    "Ken Downing",
    "Bob Drake",
    "Paddy Driver",
    "Piero Drogo",
    "Bernard de Dryver",
    "Johnny Dumfries",
    "Len Duncan",
    "Piero Dusio",
    "George Eaton",
    "Bernie Ecclestone",
    "Don Edmunds",
    "Guy Edwards",
    "Vic Elford",
    "Ed Elisian",
    "Paul Emery",
    "Tomáš Enge",
    "Paul England",
    "Marcus Ericsson",
    "Harald Ertl",
    "Nasif Estéfano",
    "Philippe Étancelin",
    "Bob Evans",
    "Corrado Fabi",
    "Teo Fabi",
    "Pascal Fabre",
    "Carlo Facetti",
    "Luigi Fagioli",
    "Jack Fairman",
    "Juan Manuel Fangio",
    "Nino Farina",
    "Walt Faulkner",
    "William Ferguson",
    "Maria Teresa de Filippis",
    "Ralph Firman",
    "Ludwig Fischer",
    "Rudi Fischer",
    "Mike Fisher",
    "Giancarlo Fisichella",
    "John Fitch",
    "Christian Fittipaldi",
    "Emerson Fittipaldi",
    "Pietro Fittipaldi",
    "Wilson Fittipaldi",
    "Theo Fitzau",
    "Pat Flaherty",
    "Jan Flinterman",
    "Ron Flockhart",
    "Myron Fohr",
    "Gregor Foitek",
    "George Follmer",
    "George Fonder",
    "Norberto Fontana",
    "Asdrúbal Fontes Bayardo",
    "Carl Forberg",
    "Gene Force",
    "Franco Forini",
    "Philip Fotheringham-Parker",
    "A. J. Foyt",
    "Giorgio Francia",
    "Don Freeland",
    "Heinz-Harald Frentzen",
    "Paul Frère",
    "Patrick Friesacher",
    "Joe Fry",
    "Hiroshi Fushida",
    "Beppe Gabbiani",
    "Bertrand Gachot",
    "Patrick Gaillard",
    "Divina Galica",
    "Nanni Galli",
    "Oscar Alfredo Gálvez",
    "Fred Gamble",
    "Howden Ganley",
    "Giedo van der Garde",
    "Frank Gardner",
    "Billy Garrett",
    "Jo Gartner",
    "Pierre Gasly",
    "Tony Gaze",
    "Geki",
    "Olivier Gendebien",
    "Marc Gené",
    "Elmer George",
    "Bob Gerard",
    "Gerino Gerini",
    "Peter Gethin",
    "Piercarlo Ghinzani",
    "Bruno Giacomelli",
    "Dick Gibson",
    "Gimax",
    "Richie Ginther",
    "Antonio Giovinazzi",
    "Yves Giraud-Cabantous",
    "Ignazio Giunti",
    "Timo Glock",
    "Helm Glöckler",
    "Paco Godia",
    "Carel Godin de Beaufort",
    "Christian Goethals",
    "Paul Goldsmith",
    "José Froilán González",
    "Óscar González",
    "Aldo Gordini",
    "Horace Gould",
    "Jean-Marc Gounon",
    "Emmanuel de Graffenried",
    "Lucas di Grassi",
    "Cecil Green",
    "Keith Greene",
    "Masten Gregory",
    "Cliff Griffith",
    "Georges Grignard",
    "Bobby Grim",
    "Romain Grosjean",
    "Olivier Grouillard",
    "Brian Gubby",
    "André Guelfi",
    "Miguel Ángel Guerra",
    "Roberto Guerrero",
    "Maurício Gugelmin",
    "Dan Gurney",
    "Esteban Gutiérrez",
    "Hubert Hahne",
    "Isack Hadjar",
    "Mike Hailwood",
    "Mika Häkkinen",
    "Bruce Halford",
    "Jim Hall",
    "Duncan Hamilton",
    "Lewis Hamilton",
    "David Hampshire",
    "Sam Hanks",
    "Walt Hansgen",
    "Mike Harris",
    "Cuth Harrison",
    "Brian Hart",
    "Brendon Hartley",
    "Gene Hartley",
    "Rio Haryanto",
    "Masahiro Hasemi",
    "Naoki Hattori",
    "Paul Hawkins",
    "Mike Hawthorn",
    "Boy Hayje",
    "Willi Heeks",
    "Nick Heidfeld",
    "Theo Helfrich",
    "Mack Hellings",
    "Brian Henton",
    "Johnny Herbert",
    "Al Herman",
    "Hans Herrmann",
    "François Hesnault",
    "Hans Heyer",
    "Damon Hill",
    "Graham Hill",
    "Phil Hill",
    "Peter Hirt",
    "David Hobbs",
    "Gary Hocking",
    "Ingo Hoffmann",
    "Bill Holland",
    "Jackie Holmes",
    "Bill Homeier",
    "Kazuyoshi Hoshino",
    "Jerry Hoyt",
    "Nico Hülkenberg",
    "Denny Hulme",
    "James Hunt",
    "Jim Hurtubise",
    "Gus Hutchison",
    "Jacky Ickx",
    "Yuji Ide",
    "Jesús Iglesias",
    "Taki Inoue",
    "Innes Ireland",
    "Eddie Irvine",
    "Chris Irwin",
    "Jean-Pierre Jabouille",
    "Jimmy Jackson",
    "Joe James",
    "John James",
    "Jean-Pierre Jarier",
    "Max Jean",
    "Stefan Johansson",
    "Eddie Johnson",
    "Leslie Johnson",
    "Bruce Johnstone",
    "Alan Jones",
    "Tom Jones",
    "Juan Jover",
    "Oswald Karch",
    "Narain Karthikeyan",
    "Ukyo Katayama",
    "Ken Kavanagh",
    "Rupert Keegan",
    "Eddie Keizan",
    "Al Keller",
    "Joe Kelly",
    "David Kennedy",
    "Loris Kessel",
    "Bruce Kessler",
    "Nicolas Kiesa",
    "Leo Kinnunen",
    "Danny Kladis",
    "Hans Klenk",
    "Peter de Klerk",
    "Christian Klien",
    "Karl Kling",
    "Ernst Klodwig",
    "Kamui Kobayashi",
    "Helmut Koinigg",
    "Heikki Kovalainen",
    "Mikko Kozarowitzky",
    "Willi Krakau",
    "Rudolf Krause",
    "Robert Kubica",
    "Kurt Kuhnke",
    "Masami Kuwashima",
    "Daniil Kvyat",
    "Robert La Caze",
    "Jacques Laffite",
    "Franck Lagorce",
    "Jan Lammers",
    "Pedro Lamy",
    "Chico Landi",
    "Hermann Lang",
    "Claudio Langes",
    "Nicola Larini",
    "Oscar Larrauri",
    "Gérard Larrousse",
    "Jud Larson",
    "Nicholas Latifi",
    "Niki Lauda",
    "Roger Laurent",
    "Giovanni Lavaggi",
    "Chris Lawrence",
    "Liam Lawson",
    "Charles Leclerc",
    "Michel Leclère",
    "Neville Lederle",
    "Geoff Lees",
    "Gijs van Lennep",
    "Arthur Legat",
    "JJ Lehto",
    "Lamberto Leoni",
    "Les Leston",
    "Pierre Levegh",
    "Bayliss Levrett",
    "Jackie Lewis",
    "Stuart Lewis-Evans",
    "Guy Ligier",
    "Arvid Lindblad",
    "Andy Linden",
    "Roberto Lippi",
    "Vitantonio Liuzzi",
    "Dries van der Lof",
    "Lella Lombardi",
    "Ricardo Londoño",
    "Ernst Loof",
    "André Lotterer",
    "Henri Louveau",
    "John Love",
    "Pete Lovely",
    "Roger Loyer",
    "Jean Lucas",
    "Jean Lucienbonnet",
    "Erik Lundgren",
    "Brett Lunger",
    "Mike MacDowel",
    "Herbert MacKay-Fraser",
    "Bill Mackey",
    "Lance Macklin",
    "Damien Magee",
    "Tony Maggs",
    "Mike Magill",
    "Umberto Maglioli",
    "Jan Magnussen",
    "Kevin Magnussen",
    "Guy Mairesse",
    "Willy Mairesse",
    "Pastor Maldonado",
    "Nigel Mansell",
    "Sergio Mantovani",
    "Johnny Mantz",
    "Robert Manzon",
    "Onofre Marimón",
    "Helmut Marko",
    "Tarso Marques",
    "Leslie Marr",
    "Tony Marsh",
    "Eugène Martin",
    "Pierluigi Martini",
    "Jochen Mass",
    "Felipe Massa",
    "Cristiano da Matta",
    "Michael May",
    "Timmy Mayer",
    "Nikita Mazepin",
    "François Mazet",
    "Gastón Mazzacane",
    "Kenneth McAlpine",
    "Perry McCarthy",
    "Ernie McCoy",
    "Johnny McDowell",
    "Jack McGrath",
    "Brian McGuire",
    "Bruce McLaren",
    "Allan McNish",
    "Graham McRae",
    "Jim McWithey",
    "Carlos Menditeguy",
    "Roberto Merhi",
    "Harry Merkel",
    "Arturo Merzario",
    "Roberto Mieres",
    "François Migault",
    "John Miles",
    "André Milhoux",
    "Chet Miller",
    "Gerhard Mitter",
    "Stefano Modena",
    "Thomas Monarch",
    "Franck Montagny",
    "Tiago Monteiro",
    "Andrea Montermini",
    "Peter Monteverdi",
    "Robin Montgomerie-Charrington",
    "Juan Pablo Montoya",
    "Gianni Morbidelli",
    "Roberto Moreno",
    "Dave Morgan",
    "Silvio Moser",
    "Bill Moss",
    "Stirling Moss",
    "Gino Munaron",
    "David Murray",
    "Luigi Musso",
    "Kazuki Nakajima",
    "Satoru Nakajima",
    "Shinji Nakano",
    "Duke Nalon",
    "Alessandro Nannini",
    "Emanuele Naspetti",
    "Felipe Nasr",
    "Massimo Natili",
    "Brian Naylor",
    "Mike Nazaruk",
    "Tiff Needell",
    "Jac Nellemann",
    "Patrick Nève",
    "John Nicholson",
    "Cal Niday",
    "Helmut Niedermayr",
    "Brausch Niemann",
    "Gunnar Nilsson",
    "Hideki Noda",
    "Lando Norris",
    "Rodney Nuckey",
    "Robert O'Brien",
    "Esteban Ocon",
    "Pat O'Connor",
    "Casimiro de Oliveira",
    "Jackie Oliver",
    "Danny Ongais",
    "Rikky von Opel",
    "Karl Oppitzhauser",
    "Fritz d'Orey",
    "Arthur Owen",
    "Carlos Pace",
    "Nello Pagani",
    "Riccardo Paletti",
    "Torsten Palm",
    "Jolyon Palmer",
    "Jonathan Palmer",
    "Olivier Panis",
    "Giorgio Pantano",
    "Massimiliano Papis",
    "Mike Parkes",
    "Reg Parnell",
    "Tim Parnell",
    "Johnnie Parsons",
    "Riccardo Patrese",
    "Al Pease",
    "Roger Penske",
    "Cesare Perdisa",
    "Sergio Pérez",
    "Luis Pérez-Sala",
    "Larry Perkins",
    "Xavier Perrot",
    "Henri Pescarolo",
    "Alessandro Pesenti-Rossi",
    "Josef Peters",
    "Ronnie Peterson",
    "Vitaly Petrov",
    "Alfredo Pián",
    "Oscar Piastri",
    "Charles Pic",
    "François Picard",
    "Ernie Pieterse",
    "Paul Pietsch",
    "André Pilette",
    "Teddy Pilette",
    "Luigi Piotti",
    "David Piper",
    "Nelson Piquet",
    "Nelson Piquet Jr.",
    "Renato Pirocchi",
    "Didier Pironi",
    "Emanuele Pirro",
    "Antônio Pizzonia",
    "Eric van de Poele",
    "Jacques Pollet",
    "Ben Pon",
    "Dennis Poore",
    "Alfonso de Portago",
    "Sam Posey",
    "Charles Pozzi",
    "Jackie Pretorius",
    "Ernesto Prinoth",
    "David Prophet",
    "Alain Prost",
    "Tom Pryce",
    "David Purley",
    "Clive Puzey",
    "Dieter Quester",
    "Ian Raby",
    "Bobby Rahal",
    "Kimi Räikkönen",
    "Hermano da Silva Ramos",
    "Pierre-Henri Raphanel",
    "Dick Rathmann",
    "Jim Rathmann",
    "Roland Ratzenberger",
    "Brian Raubenheimer",
    "Héctor Rebaque",
    "Brian Redman",
    "Jimmy Reece",
    "Ray Reed",
    "Alan Rees",
    "Clay Regazzoni",
    "Paul di Resta",
    "Carlos Reutemann",
    "Lance Reventlow",
    "Peter Revson",
    "John Rhodes",
    "Alex Ribeiro",
    "Daniel Ricciardo",
    "Ken Richardson",
    "Fritz Riess",
    "Jim Rigsby",
    "Jochen Rindt",
    "John Riseley-Prichard",
    "Giovanni de Riu",
    "Richard Robarts",
    "Pedro Rodríguez",
    "Ricardo Rodríguez",
    "Alberto Rodríguez Larreta",
    "Franco Rol",
    "Alan Rollinson",
    "Tony Rolt",
    "Bertil Roos",
    "Pedro de la Rosa",
    "Keke Rosberg",
    "Nico Rosberg",
    "Mauri Rose",
    "Louis Rosier",
    "Ricardo Rosset",
    "Alexander Rossi",
    "Huub Rothengatter",
    "Basil van Rooyen",
    "Lloyd Ruby",
    "Jean-Claude Rudaz",
    "George Russell",
    "Eddie Russo",
    "Paul Russo",
    "Troy Ruttman",
    "Peter Ryan",
    "Eddie Sachs",
    "Bob Said",
    "Carlos Sainz Jr.",
    "Eliseo Salazar",
    "Mika Salo",
    "Roy Salvadori",
    "Consalvo Sanesi",
    "Stéphane Sarrazin",
    "Logan Sargeant",
    "Takuma Sato",
    "Carl Scarborough",
    "Ludovico Scarfiotti",
    "Giorgio Scarlatti",
    "Ian Scheckter",
    "Jody Scheckter",
    "Harry Schell",
    "Tim Schenken",
    "Albert Scherrer",
    "Domenico Schiattarella",
    "Heinz Schiller",
    "Bill Schindler",
    "Jean-Louis Schlesser",
    "Jo Schlesser",
    "Bernd Schneider",
    "Rudolf Schoeller",
    "Rob Schroeder",
    "Michael Schumacher",
    "Mick Schumacher",
    "Ralf Schumacher",
    "Vern Schuppan",
    "Adolfo Schwelm Cruz",
    "Bob Scott",
    "Archie Scott Brown",
    "Piero Scotti",
    "Wolfgang Seidel",
    "Günther Seiffert",
    "Ayrton Senna",
    "Bruno Senna",
    "Dorino Serafini",
    "Chico Serra",
    "Doug Serrurier",
    "Johnny Servoz-Gavin",
    "Tony Settember",
    "Hap Sharp",
    "Brian Shawe-Taylor",
    "Carroll Shelby",
    "Tony Shelly",
    "Jo Siffert",
    "André Simon",
    "Sergey Sirotkin",
    "Rob Slotemaker",
    "Moisés Solana",
    "Alex Soler-Roig",
    "Raymond Sommer",
    "Vincenzo Sospiri",
    "Stephen South",
    "Mike Sparken",
    "Scott Speed",
    "Mike Spence",
    "Alan Stacey",
    "Gaetano Starrabba",
    "Will Stevens",
    "Chuck Stevenson",
    "Ian Stewart",
    "Jackie Stewart",
    "Jimmy Stewart",
    "Siegfried Stohr",
    "Rolf Stommelen",
    "Philippe Streiff",
    "Lance Stroll",
    "Hans Stuck",
    "Hans-Joachim Stuck",
    "Otto Stuppacher",
    "Danny Sullivan",
    "Marc Surer",
    "John Surtees",
    "Andy Sutcliffe",
    "Adrian Sutil",
    "Len Sutton",
    "Aguri Suzuki",
    "Toshio Suzuki",
    "Jacques Swaters",
    "Bob Sweikert",
    "Toranosuke Takagi",
    "Noritake Takahara",
    "Kunimitsu Takahashi",
    "Patrick Tambay",
    "Luigi Taramazzo",
    "Gabriele Tarquini",
    "Piero Taruffi",
    "Dennis Taylor",
    "Henry Taylor",
    "John Taylor",
    "Mike Taylor",
    "Trevor Taylor",
    "Marshall Teague",
    "Shorty Templeman",
    "Max de Terra",
    "André Testut",
    "Mike Thackwell",
    "Alfonso Thiele",
    "Eric Thompson",
    "Johnny Thomson",
    "Leslie Thorne",
    "Bud Tingelstad",
    "Sam Tingle",
    "Desmond Titterington",
    "Johnnie Tolan",
    "Alejandro de Tomaso",
    "Charles de Tornaco",
    "Tony Trimmer",
    "Maurice Trintignant",
    "Wolfgang von Trips",
    "Jarno Trulli",
    "Yuki Tsunoda",
    "Esteban Tuero",
    "Guy Tunmer",
    "Jack Turner",
    "Toni Ulmen",
    "Bobby Unser",
    "Jerry Unser Jr.",
    "Alberto Uría",
    "Nino Vaccarella",
    "Stoffel Vandoorne",
    "Bob Veith",
    "Jean-Éric Vergne",
    "Jos Verstappen",
    "Max Verstappen",
    "Sebastian Vettel",
    "Gilles Villeneuve",
    "Jacques Villeneuve",
    "Jacques Villeneuve",
    "Luigi Villoresi",
    "Emilio de Villota",
    "Ottorino Volonterio",
    "Jo Vonlanthen",
    "Ernie de Vos",
    "Nyck de Vries",
    "Bill Vukovich",
    "Syd van der Vyver",
    "Fred Wacker",
    "David Walker",
    "Peter Walker",
    "Lee Wallard",
    "Heini Walter",
    "Rodger Ward",
    "Derek Warwick",
    "John Watson",
    "Spider Webb",
    "Mark Webber",
    "Pascal Wehrlein",
    "Volker Weidler",
    "Wayne Weiler",
    "Karl Wendlinger",
    "Peter Westbury",
    "Chuck Weyant",
    "Ken Wharton",
    "Ted Whiteaway",
    "Graham Whitehead",
    "Peter Whitehead",
    "Bill Whitehouse",
    "Robin Widdows",
    "Eppie Wietzes",
    "Mike Wilds",
    "Jonathan Williams",
    "Roger Williamson",
    "Dempsey Wilson",
    "Desiré Wilson",
    "Justin Wilson",
    "Vic Wilson",
    "Joachim Winkelhock",
    "Manfred Winkelhock",
    "Markus Winkelhock",
    "Reine Wisell",
    "Roelof Wunderink",
    "Alexander Wurz",
    "Sakon Yamamoto",
    "Alex Yoong",
    "Alessandro Zanardi",
    "Emilio Zapico",
    "Zhou Guanyu",
    "Ricardo Zonta",
    "Renzo Zorzi",
    "Ricardo Zunino",
  ];

  //didn't do this manually either
  const teams: string[] = [
    "Alex von Falkenhausen Motorenbau",
    "Automobiles Gonfaronnaises Sportives",
    "Alfa Romeo",
    "Alfa Special",
    "AlphaTauri",
    "Alta",
    "Amon",
    "Andrea Moda",
    "Apollon",
    "Arrows",
    "Arzani-Volpini",
    "Aston Butterworth",
    "Automobili Turismo e Sport",
    "Auto Technisches Spezialzubehör",
    "British American Racing",
    "Behra-Porsche",
    "Bellasi",
    "Benetton",
    "Boro",
    "Brabham",
    "Brawn GP",
    "British Racing Motors",
    "British Racing Partnership",
    "Bugatti",
    "Caterham",
    "Cisitalia",
    "Coloni",
    "Connaught",
    "Connew",
    "Cooper Car Company",
    "Dallara",
    "De Tomaso",
    "Eagle",
    "Eifelland",
    "Emeryson",
    "Eisenacher Motorenwerk",
    "Ecurie Nationale Belge",
    "Ensign",
    "English Racing Automobiles",
    "EuroBrun",
    "Ferguson Research Ltd.",
    "FIRST",
    "Fittipaldi Automotive",
    "Fondmetal",
    "Force India",
    "Forti",
    "Frank Williams Racing Cars",
    "Frazer-Nash",
    "Fry",
    "Gilby Engineering",
    "Gordini",
    "Greifzu",
    "Hesketh",
    "Hill",
    "HRT",
    "Honda",
    "HWM",
    "Jaguar",
    "JBW",
    "Jordan",
    "Kauhsen",
    "Klenk",
    "Kojima",
    "Kurtis Kraft",
    "Lambo",
    "Lancia",
    "Larrousse",
    "LDS",
    "LEC",
    "Leyton House",
    "Life",
    "Ligier",
    "Talbot Ligier",
    "Lola",
    "Lotus",
    "Lotus",
    "Lotus",
    "Lyncar",
    "Maki",
    "Manor",
    "March",
    "Martini",
    "Marussia",
    "Maserati",
    "Matra",
    "MBM",
    "McGuire",
    "Merzario",
    "Midland",
    "Milano",
    "Minardi",
    "Onyx",
    "O.S.C.A.",
    "Osella",
    "Pacific",
    "Parnelli",
    "Penske",
    "Porsche",
    "Prost",
    "RAM",
    "Racing Point Force India",
    "Racing Point",
    "RE",
    "Renault",
    "Rebaque",
    "Rial",
    "Sauber",
    "BMW Sauber",
    "Kick Sauber",
    "Scarab",
    "Scirocco",
    "Shadow",
    "Shannon",
    "Simca-Gordini",
    "Simtek",
    "Spirit",
    "Spyker",
    "Stebro",
    "Stewart",
    "Super Aguri",
    "Surtees",
    "SVA",
    "Talbot",
    "Talbot-Lago",
    "Tec-Mec",
    "Tecno",
    "Theodore",
    "Token",
    "Toleman",
    "Toro Rosso",
    "Toyota",
    "Trojan",
    "Tyrrell",
    "Vanwall",
    "Venturi",
    "Veritas",
    "Virgin",
    "Wolf",
    "Zakspeed",
  ];

  //both past and present and future (2027)
  //taken directly from wikipedia
  const circuits: string[] = [
    "Adelaide Street Circuit",
    "Ain-Diab Circuit",
    "Aintree Motor Racing Circuit",
    "Albert Park Circuit",
    "Algarve International Circuit",
    "Autódromo do Estoril",
    "Autódromo Hermanos Rodriguez",
    "Autódromo Internacional Nelson Piquet",
    "Autodromo Internazionale del Mugello",
    "Autodromo Internazionale Enzo e Dino Ferrari",
    "Autodromo José Carlos Pace",
    "Autodromo Nazionale di Monza",
    "Autódromo Oscar y Juan Gálvez",
    "AVUS",
    "Bahrain International Circuit",
    "Baku City Circuit",
    "Brands Hatch Circuit",
    "Buddh International Circuit",
    "Bugatti Circuit",
    "Caesars Palace Grand Prix Circuit",
    "Circuit Bremgarten",
    "Circuit de Barcelona-Catalunya",
    "Circuit de Charade",
    "Circuit de Monaco",
    "Circuit de Nevers Magny-Cours",
    "Circuit de Pedralbes",
    "Circuit de Reims-Gueux",
    "Circuit de Spa-Francorchamps",
    "Circuit Dijon-Prenois",
    "Circuit Gilles Villeneuve",
    "Circuit Mont-Tremblant",
    "Circuit of the Americas",
    "Circuit Paul Ricard",
    "Circuit Zandvoort",
    "Circuit Zolder",
    "Circuito da Boavista",
    "Circuito de Monsanto",
    "Circuito Permanente de Jerez",
    "Circuito Permanente del Jarama",
    "Dallas Fair Park",
    "Detroit Street Circuit",
    "Donington Park",
    "Fuji Speedway",
    "Hockenheimring",
    "Hungaroring",
    "Indianapolis Motor Speedway",
    "Istanbul Park",
    "Jeddah Corniche Circuit",
    "Korea International Circuit",
    "Kyalami Grand Prix Circuit",
    "Las Vegas Strip Circuit",
    "Long Beach Street Circuit",
    "Lusail International Circuit",
    "Madring",
    "Marina Bay Street Circuit",
    "Miami International Autodrome",
    "Montjuïc Circuit",
    "Mosport Park",
    "Nivelles-Baulers",
    "Nürburgring",
    "Pescara Circuit",
    "Phoenix Street Circuit",
    "Prince George Circuit",
    "Red Bull Ring",
    "Riverside International Raceway",
    "Rouen-Les-Essarts",
    "Scandinavian Raceway",
    "Sebring Raceway",
    "Sepang International Circuit",
    "Shanghai International Circuit",
    "Silverstone Circuit",
    "Sochi Autodrom",
    "Suzuka International Racing Course",
    "TI Circuit Aida",
    "Valencia Street Circuit",
    "Watkins Glen International",
    "Yas Marina Circuit",
    "Zeltweg Airfield",
  ];

  const randomAll: string[] = [
    ...funFacts,
    ...quotes,
    ...drivers,
    ...teams,
    ...circuits,
  ];

  function randomItem(list: string[]) {
    return list[Math.floor(Math.random() * list.length)];
  }

  //TODO: add more commands
  const handleSubmit = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    const textArea = textAreaRef.current;
    if (!textArea) return;

    const cursorPos = textArea.selectionStart;
    const textBefore = terminalInput.substring(0, cursorPos);
    const curLine = textBefore.split("\n").length - 2; //subtract 2 since the first two lines are given automatically
    const numLines = terminalInput.split("\n").length - 2;

    if (e.key === "Enter") {
      //makes sure the new space is added first
      setTimeout(() => {
        textArea.scrollTop = textArea.scrollHeight;
      }, 0);
      const command = terminalInput.split("\n").at(-1);
      let response = "";

      if (command === "help") {
        response =
          "what is this | where am i | hello | fun fact | random all | random circuit | random driver | random quote | random team";
      } else if (command === "what is this") {
        response =
          "this is formula os, a web-based operating system dedicated to formula one lovers";
      } else if (command === "where am i") {
        response =
          "you're currently in the pit wall terminal. try typing in another command to get started!";
      } else if (command === "random all") {
        response = randomItem(randomAll);
      } else if (command === "hello") {
        response = "hello __insert name here__";
      } else if (command === "fun fact") {
        response = randomItem(funFacts);
      } else if (command === "random circuit") {
        response = randomItem(circuits);
      } else if (command === "random driver") {
        response = randomItem(drivers);
      } else if (command === "random quote") {
        response = randomItem(quotes);
      } else if (command === "random team") {
        response = randomItem(teams);
      } else {
        e.preventDefault();
      }
      setTerminalInput((prev) => prev + "\n" + response);
    }

    if (e.key === "Backspace") {
      if (
        terminalInput[terminalInput.length - 1] === "\n" ||
        curLine !== numLines
      ) {
        e.preventDefault();
      }
    }
  };

  return (
    <Window
      className="h-75 w-100"
      title="Terminal"
      startingPosition={startingPosition}
      open={terminalOpen}
      setOpen={setTerminalOpen}
      id={id}
      windowOrder={windowOrder}
      setWindowOrder={setWindowOrder}
      setOrder={setTerminalOrder}
    >
      <div className="flex flex-col terminal-text text-[#f4f3f2] w-full h-full px-2 pt-2 rounded-b-2xl bg-transparent">
        {/* <div className="w-full text-sm pb-1">Welcome to the Pit Wall.</div>
        <div className="w-full text-sm">
          Type the "help" command to see a list of all available commands.
        </div> */}
        <div className="flex flex-col w-full h-full pb-4 text-sm">
          <textarea
            ref={textAreaRef}
            value={terminalInput}
            onChange={(e) => setTerminalInput(e.target.value)}
            spellCheck={false}
            className="text-[#f4f3f2] w-full h-full resize-none leading-relaxed focus:outline-none focus:border-none focus:shadow-none overflow-y-auto custom-scrollbar  [&::-webkit-scrollbar-track]:bg-gray-800/90 
     [&::-webkit-scrollbar-thumb]:bg-black/60"
            onKeyDown={handleSubmit}
          />
        </div>
      </div>
    </Window>
  );
}
